# OAM 6G Base Configuration
# This file contains all common parameters used across different configurations

# System parameters
system:
  frequency: 28.0e9          # 28 GHz mmWave
  bandwidth: 400e6           # 400 MHz
  tx_power_dBm: 30.0         # 30 dBm transmit power
  noise_figure_dB: 8.0       # 8 dB noise figure
  noise_temp: 290.0          # 290 K noise temperature

# OAM parameters
oam:
  min_mode: 1                # Minimum OAM mode
  max_mode: 8                # Maximum OAM mode (increased for better coverage)
  mode_spacing: 1            # Mode spacing
  beam_width: 0.03           # 30 mrad beam width

# Environment parameters
environment:
  pointing_error_std: 0.005  # 5 mrad pointing error
  rician_k_factor: 8.0       # 8 dB Rician K-factor
  turbulence_strength: 1e-14 # Cn² value (typical clear air)
  humidity: 50.0             # Relative humidity (%)
  temperature: 20.0          # Temperature (°C)
  pressure: 101.3            # Atmospheric pressure (kPa)

# Enhanced parameters
enhanced_params:
  antenna_efficiency: 0.75   # 75% antenna efficiency
  implementation_loss_dB: 3.0 # 3 dB implementation losses

# User Mobility
mobility:
  max_speed: 5.0             # 5 m/s maximum speed (walking/slow vehicle)
  min_speed: 0.5             # 0.5 m/s minimum speed
  direction_change_prob: 0.1 # 10% probability of direction change per step

# Base RL parameters
rl_base:
  # Network architecture
  network:
    state_dim: 8             # [SINR, distance, velocity, current_mode, etc.]
    action_dim: 3            # [STAY, UP, DOWN]
    hidden_layers: [128, 128] # Hidden layer sizes
    activation: "relu"       # Activation function

  # Replay buffer
  replay_buffer:
    capacity: 50000          # Replay buffer capacity
    min_samples_to_learn: 1000 # Minimum samples before learning starts

  # Exploration
  exploration:
    epsilon_start: 1.0       # Initial exploration rate
    epsilon_end: 0.01        # Final exploration rate
    epsilon_decay: 0.99      # Exploration decay rate

  # Evaluation
  evaluation:
    eval_episodes: 10        # Number of episodes for evaluation
    eval_frequency: 50       # Episodes between evaluations
    save_model_frequency: 50 # Episodes between model saves