# OAM 6G Hierarchical Configuration System
# This file defines the configuration hierarchy and inheritance structure

# Configuration Hierarchy:
# 1. base_config.yaml - Base parameters (inherited by all)
# 2. simulation_config.yaml - Simulation-specific parameters
# 3. rl_config.yaml - RL-specific parameters
# 4. stable_reward_config.yaml - Stable reward parameters
# 5. extended_config.yaml - Extended training parameters

# Inheritance Structure:
# base_config.yaml
# ├── simulation_config.yaml (inherits from base)
# │   ├── rl_config.yaml (inherits from simulation)
# │   │   ├── stable_reward_config.yaml (inherits from rl)
# │   │   └── extended_config.yaml (inherits from rl)
# │   └── extended_training_config.yaml (inherits from simulation)

# Configuration Types:
# - base: Common parameters used by all configurations
# - simulation: Physics and environment parameters
# - rl: Reinforcement learning parameters
# - stable_reward: Stable reward function parameters
# - extended: Extended training parameters

# Usage:
# - For basic RL training: rl_config.yaml
# - For stable reward training: stable_reward_config.yaml
# - For extended training: extended_config.yaml
# - For custom configurations: Inherit from appropriate base 