# OAM 6G Extended Training Configuration
# Configuration for longer training runs with adjusted parameters

# Extended training parameters
training:
  num_episodes: 1000         # Extended number of episodes
  max_steps_per_episode: 500 # Extended episode length
  batch_size: 128            # Batch size for training
  learning_rate: 0.0001      # Learning rate
  gamma: 0.99                # Discount factor
  target_update_freq: 20     # Less frequent target network updates

# Extended exploration parameters
exploration:
  epsilon_start: 1.0         # Initial exploration rate
  epsilon_end: 0.01          # Final exploration rate
  epsilon_decay: 0.995       # Slower decay for longer training

# Extended replay buffer
replay_buffer:
  capacity: 100000           # Larger buffer for longer training
  min_samples_to_learn: 1000 # Minimum samples before learning

# Extended evaluation parameters
evaluation:
  eval_episodes: 20          # More episodes for better evaluation
  eval_frequency: 100        # Less frequent evaluations
  save_model_frequency: 100  # Less frequent model saving