# OAM 6G Stable Reward Configuration
# Extends rl_config.yaml with stable reward parameters

# Stable reward parameters
stable_reward:
  smoothing_factor: 0.7      # Exponential smoothing factor (0-1)
  window_size: 10            # Size of moving average window
  reward_scale: 2.0          # Scaling factor for reward
  reward_min: -10.0          # Minimum reward value
  reward_max: 10.0           # Maximum reward value
  sinr_scaling_factor: 0.1   # Scale SINR contribution to reward

# Modified reward parameters for stable version
reward:
  throughput_factor: 5.0     # Increased weight for throughput
  handover_penalty: 0.5      # Penalty for mode handovers
  outage_penalty: 5.0        # Penalty for SINR below threshold
  sinr_threshold: -5.0       # SINR threshold for outage (dB)